DeteksiJalanRusak.Web/ViewComponents/ToastrViewComponent.cs
using DeteksiJalanRusak.Web.Models;
using DeteksiJalanRusak.Web.Services.Toastr;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace DeteksiJalanRusak.Web.ViewComponents;

public class ToastrViewComponent : ViewComponent
{
    private readonly IToastrNotificationService _notificationService;

    public ToastrViewComponent(IToastrNotificationService notificationService)
    {
        _notificationService = notificationService;
    }

    public IViewComponentResult Invoke(ToastrOptions globalOptions)
    {
        string globalOptionsJson = JsonConvert.SerializeObject(globalOptions, new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            Formatting = Formatting.Indented,
        });
        return View((globalOptionsJson, _notificationService.GetNotificationJson()));
    }
}

DeteksiJalanRusak.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistem Deteksi Kerusakan Jalan</title>
@*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
@*     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/datatables/datatables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/components.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    @* <link rel="stylesheet" href="~/DeteksiJalanRusak.Web.styles.css" asp-append-version="true" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: black">Sistem Deteksi Kerusakan Jalan</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="ml-auto">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> <span>Beranda</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Panduan"><i class="fas fa-book"></i> <span>Panduan</span></a>
                            </li>
                        </ul>
                    </div>                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-right">
        <div class="container">
            &copy; 2025 - Sistem Deteksi Kerusakan Jalan
        </div>
    </footer>
    <script src="~/js/app.min.js" asp-append-version="true"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    <script src="~/js/datatables.js" asp-append-version="true"></script>

    @{
        var globalOptions = new ToastrOptions
        {
            closeButton = true,
            progressBar = true,
            newestOnTop = true,
            preventDuplicates = false,
            timeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
            extendedTimeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
            showDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
            hideDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
            showEasing = Easings.Swing,
            hideEasing = Easings.Swing,
            showMethod = AnimationMethods.FadeIn,
            hideMethod = AnimationMethods.FadeOut,
            positionClass = PositionClasses.TopRight,
        };
    }

    <vc:toastr global-options=globalOptions></vc:toastr>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>