DeteksiJalanRusak.Web/Entities/Segmen.cs
using DeteksiJalanRusak.Web.Models;

namespace DeteksiJalanRusak.Web.Entities;

public class Segmen
{
    public int Id { get; set; }

    public required double LuasSampel { get; set; }

    public List<DensityDV> DensityDVs() => [.. DaftarFoto
        .Where(x => x.AdaKertas)
        .SelectMany(x => x.DaftarKerusakan)
        .GroupBy(x => new { x.Label, x.Kondisi })
        .Select(x => new DensityDV
        {
            DistressDensity = x.Sum(x => x.LuasPersegi) / LuasSampel * 100d,
            Kondisi = x.Key.Kondisi,
            Label = x.Key.Label,
            TotalLuas = x.Sum(x => x.LuasPersegi)
        })
        .OrderByDescending(x => x.DeductValue)];

    public PCIResult? MetodePCI()
    {
        var densityDVs = DensityDVs();
        if (densityDVs.Count == 0) return null;

        var dvLebihDari2 = densityDVs.Where(x => x.DeductValue > 2d).OrderByDescending(x => x.DeductValue);
        var dvKurangDariSamaDengan2 = densityDVs.Where(x => x.DeductValue <= 2d).OrderByDescending(x => x.DeductValue);
        var dvMax = densityDVs.Select(x => x.DeductValue).Max();
        var mi = 1 + (9 / 98 * (100 - dvMax));

        var q = Math.Clamp(dvLebihDari2.Count(), HelperFunctions.QMIN, HelperFunctions.QMAX);
        var tdv = dvLebihDari2.Sum(x => x.DeductValue) + dvKurangDariSamaDengan2.Sum(x => x.DeductValue);
        var cdvMax = HelperFunctions.TdvToCdv(tdv, q);

        var qMax = q;
        var tdvMax = tdv;

        for (int i = q - 1; i >= 1; i--)
        {
            tdv = dvLebihDari2.Take(i).Sum(x => x.DeductValue) + (2d * (q - i)) + dvKurangDariSamaDengan2.Sum(x => x.DeductValue);
            var cdv = HelperFunctions.TdvToCdv(tdv, i);
            if (cdv > cdvMax)
            {
                tdvMax = tdv;
                qMax = i;
                cdvMax = cdv;
            }
        }

        var pci = 100 - cdvMax;

        return new PCIResult
        {
            PCI = pci,
            CDVMax = cdvMax,
            TDVMax = tdvMax,
            QMax = qMax,
            MI = mi,
        };
    }

    public Analisis Analisis { get; set; }
    public List<FotoKerusakan> DaftarFoto { get; set; } = [];
}

DeteksiJalanRusak.Web/Controllers/AnalisisController.cs
using DeteksiJalanRusak.Web.Database;
using DeteksiJalanRusak.Web.Entities;
using DeteksiJalanRusak.Web.Models.AnalisisModels;
using DeteksiJalanRusak.Web.Services.Toastr;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DeteksiJalanRusak.Web.Controllers;

public class AnalisisController : Controller
{
    private readonly AppDbContext _context;
    private readonly IToastrNotificationService _notificationService;
    private readonly ILogger<AnalisisController> _logger;

    public AnalisisController(
        AppDbContext context,
        IToastrNotificationService notificationService,
        ILogger<AnalisisController> logger)
    {
        _context = context;
        _notificationService = notificationService;
        _logger = logger;
    }

    public async Task<IActionResult> Detail(int id)
    {
        var analisis = await _context
            .TblAnalisis
            .Include(x => x.DaftarSegmen).ThenInclude(x => x.DaftarFoto).ThenInclude(x => x.DaftarKerusakan)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (analisis is null) return NotFound();

        return View(analisis);
    }

    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if (await _context.TblAnalisis.AnyAsync(x => x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        var analisis = new Analisis
        {
            Lokasi = vm.Lokasi,
            Nama = vm.Nama,
            Pembuat = vm.Pembuat
        };

        _context.TblAnalisis.Add(analisis);
        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Edit(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        return View(new EditVM
        {
            Id = id,
            Nama = analisis.Nama,
            Lokasi = analisis.Lokasi,
            Pembuat = analisis.Pembuat
        });
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == vm.Id);
        if (analisis is null) return NotFound();

        if (await _context.TblAnalisis.AnyAsync(x => x.Id != analisis.Id && x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        analisis.Nama = vm.Nama;
        analisis.Lokasi = vm.Lokasi;
        analisis.Pembuat = vm.Pembuat;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public async Task<IActionResult> Hapus(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        _context.TblAnalisis.Remove(analisis);

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return RedirectToAction(nameof(Index));
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }
}

DeteksiJalanRusak.Web/Controllers/FotoController.cs
using DeteksiJalanRusak.Web.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DeteksiJalanRusak.Web.Controllers;

public class FotoController : Controller
{
    private readonly AppDbContext _context;

    public FotoController(AppDbContext context)
    {
        _context = context;
    }

    [Route("[action]")]
    public async Task<IActionResult> FotoKerusakan(int id)
    {
        var foto = await _context.TblFoto.FirstOrDefaultAsync(x => x.Id == id);
        if (foto is null) return NotFound();

        return File(foto.Image, "image/jpg");
    }

    [Route("[action]")]
    public async Task<IActionResult> MaskKertas(int id)
    {
        var foto = await _context.TblFoto.FirstOrDefaultAsync(x => x.Id == id);
        if (foto is null || !foto.AdaKertas) return NotFound();

        return File(foto.MaskKertas, "image/jpg");
    }

    [Route("[action]")]
    public async Task<IActionResult> MaskKerusakan(int id)
    {
        var kerusakan = await _context.TblKerusakan.FirstOrDefaultAsync(x => x.Id == id);
        if (kerusakan is null) return NotFound();

        return File(kerusakan.Mask, "image/jpg");
    }
}

DeteksiJalanRusak.Web/Controllers/SegmenController.cs
using DeteksiJalanRusak.Web.Configurations;
using DeteksiJalanRusak.Web.Database;
using DeteksiJalanRusak.Web.Entities;
using DeteksiJalanRusak.Web.Extensions;
using DeteksiJalanRusak.Web.Models;
using DeteksiJalanRusak.Web.Models.SegmenModels;
using DeteksiJalanRusak.Web.Services.FileServices;
using DeteksiJalanRusak.Web.Services.Toastr;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkiaSharp;
using YoloDotNet;
using YoloDotNet.Core;
using YoloDotNet.Enums;
using YoloDotNet.Extensions;
using YoloDotNet.Models;

namespace DeteksiJalanRusak.Web.Controllers;

public class SegmenController : Controller
{
    public const double LEBAR_KERTASA4_CM = 21;
    public const double PANJANG_KERTASA4_CM = 29.7;
    public const double LEBAR_KERTASA4_M = LEBAR_KERTASA4_CM / 100;
    public const double PANJANG_KERTASA4_M = PANJANG_KERTASA4_CM / 100;
    public const double LUAS_KERTASA4_CM2 = LEBAR_KERTASA4_CM * PANJANG_KERTASA4_CM;
    public const double LUAS_KERTASA4_M2 = LUAS_KERTASA4_CM2 / 10000;

    private readonly SegmentationDrawingOptions _drawingOptions;
    private readonly ModelConfigurationOptions _modelConfigurationOptions;
    private readonly AppDbContext _appDbContext;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IFileService _fileService;
    private readonly IToastrNotificationService _notificationService;
    private readonly ILogger<SegmenController> _logger;

    public SegmenController(
        ModelConfigurationOptions modelConfigurationOptions,
        AppDbContext appDbContext,
        IWebHostEnvironment webHostEnvironment,
        IFileService fileService,
        IToastrNotificationService notificationService,
        ILogger<SegmenController> logger)
    {
        _drawingOptions = new SegmentationDrawingOptions
        {
            DrawBoundingBoxes = true,
            DrawConfidenceScore = true,
            DrawLabels = true,
            EnableFontShadow = true,
            Font = SKTypeface.Default,
            FontSize = 18,
            FontColor = SKColors.White,
            DrawLabelBackground = true,
            EnableDynamicScaling = true,
            BorderThickness = 2,
            BoundingBoxOpacity = 128,
            DrawSegmentationPixelMask = true
        };
        _modelConfigurationOptions = modelConfigurationOptions;
        _appDbContext = appDbContext;
        _webHostEnvironment = webHostEnvironment;
        _fileService = fileService;
        _notificationService = notificationService;
        _logger = logger;
    }

    public IActionResult Tambah(int idAnalisis) => View(new TambahVM { IdAnalisis = idAnalisis });

    [HttpPost]
    [RequestSizeLimit(100_000_000)]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var analisis = await _appDbContext.TblAnalisis.FirstOrDefaultAsync(x => x.Id == vm.IdAnalisis);
        if (analisis is null)
        {
            _notificationService.AddError("Analisis tidak ditemukan");
            return RedirectToActionPermanent("Index", "Analisis");
        }

        var tasks = vm.FormFiles.Select(x => _fileService.ProcessFormFile<TambahVM>(x, [".jpg", ".jpeg", ".png"], 0, long.MaxValue)).ToList();
        var daftarFoto = await Task.WhenAll(tasks);

        var failures = daftarFoto.Where(x => x.IsFailure);
        if (failures.Any())
        {
            ModelState.AddModelError(nameof(vm.FormFiles), string.Join("\n", failures.Select(x => x.Error.Message)));
            return View(vm);
        }

        var segmen = new Segmen
        {
            LuasSampel = vm.LuasSampel,
            Analisis = analisis,
            DaftarFoto = []
        };

        using var yolo = new Yolo(new YoloOptions
        {
            OnnxModel = _modelConfigurationOptions.FilePath,
            ExecutionProvider = new CpuExecutionProvider(),
            ImageResize = ImageResize.Stretched,
            SamplingOptions = new(SKFilterMode.Nearest, SKMipmapMode.None)
        });

        foreach (var foto in daftarFoto)
        {
            using var image = SKBitmap.Decode(foto.Value);
            var results = yolo.RunSegmentation(image, confidence: 0.5, pixelConfedence: 0.5, iou: 0.7);
            image.Draw(results, _drawingOptions);

            var fotoKerusakan = new FotoKerusakan
            {
                AdaKertas = false,
                FileName = vm.FormFiles[Array.IndexOf(daftarFoto, foto)].FileName,
                Image = image.Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                Lebar = image.Width,
                Tinggi = image.Height,
                DaftarKerusakan = [.. results.Where(x => x.Label.Name != LabelEnum.Kertas.ToString()).Select(x => new Kerusakan
                {
                    Label = x.Label.Name.DehumanizeTo<LabelEnum>(),
                    Mask = x.BitPackedPixelMask.UnpackToBitmap(x.BoundingBox.Width, x.BoundingBox.Height).Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                    Luas = 0,
                    Panjang = 0,
                    Lebar = 0,
                    LebarPiksel = 0,
                    TinggiPiksel = 0,
                })]
            };

            var kertas = results.FirstOrDefault(s => s.Label.Name == LabelEnum.Kertas.ToString());

            if (kertas is not null)
            {
                var totalPixel = kertas.BitPackedPixelMask.Count(x => x != 0);
                var m2PerPixel = LUAS_KERTASA4_M2 / totalPixel;

                var mPerPixel = PANJANG_KERTASA4_M /
                    (kertas.BoundingBox.Width > kertas.BoundingBox.Height ? kertas.BoundingBox.Width : kertas.BoundingBox.Height);

                fotoKerusakan.AdaKertas = true;

                fotoKerusakan.MaskKertas = kertas.BitPackedPixelMask.UnpackToBitmap(kertas.BoundingBox.Width, kertas.BoundingBox.Height).Encode(SKEncodedImageFormat.Jpeg, 70).ToArray();

                fotoKerusakan.M2PerPiksel = m2PerPixel;
                fotoKerusakan.MPerPiksel = mPerPixel;
                fotoKerusakan.LuasKertas = kertas.BitPackedPixelMask.Count(x => x != 0) * m2PerPixel;
                fotoKerusakan.PanjangKertas = kertas.BoundingBox.Height * mPerPixel;
                fotoKerusakan.LebarKertas = kertas.BoundingBox.Width * mPerPixel;
                fotoKerusakan.TinggiPikselKertas = kertas.BoundingBox.Height;
                fotoKerusakan.LebarPikselKertas = kertas.BoundingBox.Width;

                fotoKerusakan.DaftarKerusakan = [];

                foreach (var segmentation in results.Where(x => x.Label.Name != LabelEnum.Kertas.ToString()))
                {
                    fotoKerusakan.DaftarKerusakan.Add(new Kerusakan
                    {
                        Label = segmentation.Label.Name.DehumanizeTo<LabelEnum>(),
                        Mask = segmentation
                            .BitPackedPixelMask
                            .UnpackToBitmap(segmentation.BoundingBox.Width, segmentation.BoundingBox.Height)
                            .Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                        Luas = segmentation.BitPackedPixelMask.Count(x => x != 0) * m2PerPixel,
                        Panjang = segmentation.BoundingBox.Height * mPerPixel,
                        Lebar = segmentation.BoundingBox.Width * mPerPixel,
                        TinggiPiksel = segmentation.BoundingBox.Height,
                        LebarPiksel = segmentation.BoundingBox.Width,
                    });
                }
            }

            segmen.DaftarFoto.Add(fotoKerusakan);
        }

        _appDbContext.TblSegmen.Add(segmen);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());
            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");

        return RedirectToActionPermanent("Detail", new { id = segmen.Id });
    }

    public async Task<IActionResult> Edit(int id, string? returnUrl = null)
    {
        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == id);
        if (segmen is null) return NotFound();

        return View(new EditVM
        {
            Id = id,
            LuasSampel = segmen.LuasSampel,
            ReturnUrl = returnUrl ?? Url.ActionLink("Detail", "Analisis", new { id = segmen.Analisis.Id })!
        });
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == vm.Id);
        if (segmen is null) return NotFound();

        segmen.LuasSampel = vm.LuasSampel;

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());
            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectPermanent(vm.ReturnUrl);
    }

    public async Task<IActionResult> Detail(int id)
    {
        var segmen = await _appDbContext
            .TblSegmen
            .Include(x => x.Analisis)
            .Include(x => x.DaftarFoto).ThenInclude(x => x.DaftarKerusakan)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (segmen is null) return NotFound();

        return View(segmen);
    }

    [HttpPost]
    public async Task<IActionResult> Hapus(int id)
    {
        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == id);
        if (segmen is null) return NotFound();

        var idAnalisis = segmen.Analisis.Id;

        _appDbContext.TblSegmen.Remove(segmen);

DeteksiJalanRusak.Web/Views/Segmen/Detail.cshtml
@using DeteksiJalanRusak.Web.Controllers
@model Segmen

@{
    ViewData["Title"] = "Detail Segmen";
}

@{
    var densityDvs = Model.DensityDVs();
    var pciResult = Model.MetodePCI();
}

<div class="card card-secondary mb-2">
    <div class="card-header">
        <h4>Detail Segmen</h4>
        <div class="ml-auto">
            <a asp-action="Detail" asp-controller="Analisis" asp-route-id="@Model.Analisis.Id" class="btn btn-primary">Kembali</a>
        </div>
        <div class="ml-2">
            <a asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Context.Request.AbsoluteUri()" class="btn btn-warning">Edit</a>
        </div>
        <div class="ml-2">
            <form asp-action="Hapus" asp-route-id="@Model.Id" style="display:inline">
                <button class="btn btn-danger">Hapus</button>
            </form>
        </div>
    </div>
    <div class="card-body">
        <p>Luas Sampel : @Model.LuasSampel m<sup>2</sup></p>                       
    </div>
</div>

<div class="card mb-2">
    <div class="card-header">
        <h4>Ukuran Kertas Asli</h4>
    </div>
    <div class="card-body">
        <p>Dimensi Kertas (m) : @SegmenController.PANJANG_KERTASA4_M x @SegmenController.LEBAR_KERTASA4_M</p>
        <p>Luas Kertas (m<sup>2</sup>) : @SegmenController.LUAS_KERTASA4_M2</p>
    </div>
</div>

@if (densityDvs.Count > 0)
{
    <div class="card mb-2">
        <div class="card-header">
            <h4>Daftar Nilai Density dan Deduct Value</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-akun1">
                    <thead>
                        <tr>
                            <th>Kerusakan</th>
                            <th>Kondisi</th>
                            <th>Total Luas (m<sup>2</sup>)</th>
                            <th>Density (%)</th>
                            <th>Deduct Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var dv in densityDvs)
                        {
                            <tr>
                                <td>@dv.Label.Humanize()</td>
                                <td>@dv.Kondisi.Humanize()</td>
                                <td>@dv.TotalLuas</td>
                                <td>@dv.DistressDensity.ToString("F5")</td>
                                <td>@dv.DeductValue</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>            
        </div>
    </div>   
}

@if (pciResult is not null)
{
    <div class="card mb-2">
        <div class="card-header">
            <h4>Hasil Metode PCI</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="table-akun2">
                    <thead>
                        <tr>
                            <th>Mi</th>
                            <th>q<sub>Max</sub></th>
                            <th>TDV<sub>Max</sub></th>
                            <th>CDV<sub>Max</sub></th>
                            <th>PCI</th>
                            <th>Kondisi</th>
                            <th>Jenis Penanganan</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@pciResult.MI</td>
                            <td>@pciResult.QMax</td>
                            <td>@pciResult.TDVMax</td>
                            <td>@pciResult.CDVMax</td>
                            <td>@pciResult.PCI</td>
                            <td>@pciResult.Kondisi</td>
                            <td>@pciResult.JenisPenanganan</td>
                        </tr>
                    </tbody>
                </table>
            </div>            
        </div>
    </div>  
}


<div class="card mb-2">
    <div class="card-header">
        <h4>Daftar Kerusakan</h4>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="save-stage">
                <thead>
                    <tr>
                        <th rowspan="2"></th>
                        <th rowspan="2">File Name</th>
                        <th rowspan="2">Ukuran Foto</th>
                        <th rowspan="2">m/pixel</th>
                        <th rowspan="2">m<sup>2</sup>/pixel</th>
                        <th rowspan="2">Luas (Kertas)</th>
                        <th rowspan="2">Luas Persegi (Kertas)</th>
                        <th rowspan="2">Panjang (Kertas)</th>
                        <th rowspan="2">Lebar (Kertas)</th>
                        <th rowspan="2">Mask (Kertas)</th>
                        <th colspan="7">Kerusakan</th>
                    </tr>
                    <tr>
                        <th>Jenis</th>
                        <th>Luas</th>
                        <th>Luas Persegi</th>
                        <th>Panjang</th>
                        <th>Lebar</th>
                        <th>Kondisi</th>
                        <th>Mask</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var foto in Model.DaftarFoto)
                    {
                        var rowspan = foto.DaftarKerusakan.Count + 1;
                        <tr>
                            <td rowspan="@rowspan">
                                <img src="@Url.Action(nameof(FotoController.FotoKerusakan), "Foto", new { id = foto.Id})" height="200" />
                            </td>
                            <td rowspan="@rowspan">@foto.FileName</td>
                            <td rowspan="@rowspan">@foto.Lebar x @foto.Tinggi Pixel</td>
                            @if (foto.AdaKertas)
                            {
                                <td rowspan="@rowspan">@foto.MPerPiksel.ToString("F10")</td>
                                <td rowspan="@rowspan">@foto.M2PerPiksel.ToString("F10")</td>
                                <td rowspan="@rowspan">@foto.LuasKertas m<sup>2</sup></td>
                                <td rowspan="@rowspan">@foto.LuasPersegiKertas m<sup>2</sup></td>
                                <td rowspan="@rowspan">@foto.PanjangKertas m</td>
                                <td rowspan="@rowspan">@foto.LebarKertas m</td>
                                <td rowspan="@rowspan">
                                    <p>@foto.LebarPikselKertas x @foto.TinggiPikselKertas Pixel</p>
                                    <img style="background-color:black" src="@Url.Action(nameof(FotoController.MaskKertas), "Foto", new { id = foto.Id })" height="200" />
                                </td>
                            }
                            else
                            {
                                <td rowspan="@rowspan" colspan="7">Objek Pengukur (Kertas) tidak ditemukan</td>
                            }
                        </tr>
                        @foreach (var kerusakan in foto.DaftarKerusakan)
                        {
                            <tr>
                                <td>@kerusakan.Label.Humanize()</td>
                                @if (foto.AdaKertas)
                                {
                                    <td>@kerusakan.Luas.ToString("F5") m<sup>2</sup></td>
                                    <td>@kerusakan.LuasPersegi.ToString("F5") m<sup>2</sup></td>
                                    <td>@kerusakan.Panjang.ToString("F5") m</td>
                                    <td>@kerusakan.Lebar.ToString("F5") m</td>
                                    <td>@kerusakan.Kondisi</td>
                                }
                                else
                                {
                                    <td rowspan="@rowspan - 1" colspan="5">Objek Pengukur (Kertas) tidak ditemukan</td>
                                }
                                <td>
                                    <p>@kerusakan.LebarPiksel x @kerusakan.TinggiPiksel Pixel</p>
                                    <img style="background-color:black" src="@Url.Action(nameof(FotoController.MaskKerusakan), "Foto", new { id = kerusakan.Id })" height="200" />
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>        
    </div>
</div>

DeteksiJalanRusak.Web/Views/Segmen/Edit.cshtml
@using DeteksiJalanRusak.Web.Models.SegmenModels
@model EditVM

@{
    ViewData["Title"] = "Edit Segmen";
}

<div class="card card-primary">
    <div class="card-header">
        <h4> Edit Segmen</h4>
    </div>

    <div class="card-body">
        <form asp-action="Edit" asp-route-id="@Model.Id" asp-route-returnUrl="@Model.ReturnUrl" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.LuasSampel"></label>
                <input asp-for="@Model.LuasSampel" class="form-control" />
                <span asp-validation-for="@Model.LuasSampel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="@Model.ReturnUrl" class="btn btn-danger">Batal</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DeteksiJalanRusak.Web/Views/Segmen/Tambah.cshtml
@using DeteksiJalanRusak.Web.Models.SegmenModels
@model TambahVM

<div class="card card-primary">
    <div class="card-header">
        <h4> Tambah Segmen</h4>
    </div>

    <div class="card-body">
        <form asp-action="Tambah" asp-route-idAnalisis="@Model.IdAnalisis" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.FormFiles"></label>
                <input asp-for="@Model.FormFiles" type="file" multiple class="form-control" />
                <span asp-validation-for="@Model.FormFiles" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.LuasSampel"></label>
                <input asp-for="@Model.LuasSampel" class="form-control" />
                <span asp-validation-for="@Model.LuasSampel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a asp-action="Detail" asp-controller="Analisis" asp-route-id="@Model.IdAnalisis" class="btn btn-danger">Batal</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}