DeteksiJalanRusak.Web/Models/Home/DensityDV.cs
namespace DeteksiJalanRusak.Web.Models.Home;

public class DensityDV
{
    public required KondisiKerusakan Kondisi { get; set; }
    public required LabelEnum Label { get; set; }
    public required double DistressDensity { get; set; }
    public required double TotalLuas { get; set; }

    public double DeductValue => DistressDensityToDV.DDToDV(Label, DistressDensity, Kondisi);
}

DeteksiJalanRusak.Web/Models/Home/IndexVM.cs
using System.ComponentModel.DataAnnotations;

namespace DeteksiJalanRusak.Web.Models.Home;

public class IndexVM
{
    [Display(Name = "Foto-Foto Kerusakan dan Kertas (.jpg, .jpeg, .png)")]
    [Required(ErrorMessage = "Minimal 1 foto harus dipilih")]
    [MinLength(1)]
    public List<IFormFile> FormFiles { get; set; } = [];

    [Display(Name = "Luas Sampel (meter persegi)")]
    [Required(ErrorMessage = "Harus diisi")]
    public double LuasSampel { get; set; } = 200;

    public List<ResultVM> ResultVMs { get; set; } = [];
    public List<DensityDV> DensityDVs{ get; set; } = [];
    public PCIResult? PCIResult { get; set; }
}

DeteksiJalanRusak.Web/Controllers/AnalisisController.cs
using DeteksiJalanRusak.Web.Database;
using DeteksiJalanRusak.Web.Entities;
using DeteksiJalanRusak.Web.Models.AnalisisModels;
using DeteksiJalanRusak.Web.Services.Toastr;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DeteksiJalanRusak.Web.Controllers;

public class AnalisisController : Controller
{
    private readonly AppDbContext _context;
    private readonly IToastrNotificationService _notificationService;
    private readonly ILogger<AnalisisController> _logger;

    public AnalisisController(
        AppDbContext context,
        IToastrNotificationService notificationService,
        ILogger<AnalisisController> logger)
    {
        _context = context;
        _notificationService = notificationService;
        _logger = logger;
    }

    public async Task<IActionResult> Detail(int id)
    {
        var analisis = await _context
            .TblAnalisis
            .Include(x => x.DaftarSegmen).ThenInclude(x => x.DaftarFoto).ThenInclude(x => x.DaftarKerusakan)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (analisis is null) return NotFound();

        return View(analisis);
    }

    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if (await _context.TblAnalisis.AnyAsync(x => x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        var analisis = new Analisis
        {
            Lokasi = vm.Lokasi,
            Nama = vm.Nama,
            Pembuat = vm.Pembuat
        };

        _context.TblAnalisis.Add(analisis);
        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Edit(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        return View(new EditVM
        {
            Id = id,
            Nama = analisis.Nama,
            Lokasi = analisis.Lokasi,
            Pembuat = analisis.Pembuat
        });
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == vm.Id);
        if (analisis is null) return NotFound();

        if (await _context.TblAnalisis.AnyAsync(x => x.Id != analisis.Id && x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        analisis.Nama = vm.Nama;
        analisis.Lokasi = vm.Lokasi;
        analisis.Pembuat = vm.Pembuat;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public async Task<IActionResult> Hapus(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        _context.TblAnalisis.Remove(analisis);

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return RedirectToAction(nameof(Index));
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }
}

DeteksiJalanRusak.Web/Controllers/HomeController.cs
using DeteksiJalanRusak.Web.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DeteksiJalanRusak.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;

        public HomeController(
            AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index() => View(await _context.TblAnalisis.ToListAsync());

        public IActionResult Panduan() => View();
    }
}

DeteksiJalanRusak.Web/Views/Home/Index.cshtml
@model List<Analisis>

@{
    ViewData["Title"] = "Beranda";
}

<div class="card card-primary">
    @*     <div class="card-header">

    </div> *@

    <div class="card-body">
        <a asp-action="Tambah" asp-controller="Analisis" class="btn btn-primary mb-3">Buat Analisis Baru</a>

        <div class="table-responsive">
            <table class="table table-striped table-hover" id="table-akunn">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Pembuat</th>
                        <th>Lokasi</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var analisis in Model)
                    {
                        <tr>
                            <td>@analisis.Nama</td>
                            <td>@analisis.Pembuat</td>
                            <td>@analisis.Lokasi</td>
                            <td>
                                <a class="btn btn-icon icon-left btn-warning" asp-action="Detail" asp-controller="Analisis" asp-route-id="@analisis.Id"><i class="fas fa-eye"></i> Detail</a>
                                <a class="btn btn-icon icon-left btn-primary" asp-action="Edit" asp-controller="Analisis" asp-route-id="@analisis.Id"><i class="fas fa-pencil-alt"></i> Edit</a>

                                <form asp-action="Hapus" asp-route-id="@analisis.Id" asp-controller="Analisis" style="display:inline">
                                    <button class="btn btn-icon icon-left btn-danger" type="submit"><i class="fas fa-trash"></i> Hapus</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DeteksiJalanRusak.Web/Views/Home/Panduan.cshtml
<embed class="pdf" src="/panduan/buku panduan.pdf"
       width="100%"
       height="600" />