DeteksiJalanRusak.Web/Entities/Analisis.cs
using DeteksiJalanRusak.Web.Models;

namespace DeteksiJalanRusak.Web.Entities;

public class Analisis
{
    public int Id { get; set; }
    public required string Nama { get; set; }
    public required string Lokasi { get; set; }
    public required string Pembuat { get; set; }

    public double RataRataPCI
    {
        get
        {
            var daftarPCI = DaftarSegmen.Select(x => x.MetodePCI()).Where(x => x != null).Select(x => x!.PCI);

            return daftarPCI.Any() ? daftarPCI.Average() : 0;
        }
    }

    public string Kondisi => HelperFunctions.KondisiPCI(RataRataPCI);
    public string JenisPenanganan => HelperFunctions.JenisPenangananPCI(RataRataPCI);

    public List<Segmen> DaftarSegmen { get; set; } = [];
}

DeteksiJalanRusak.Web/Controllers/AnalisisController.cs
using DeteksiJalanRusak.Web.Database;
using DeteksiJalanRusak.Web.Entities;
using DeteksiJalanRusak.Web.Models.AnalisisModels;
using DeteksiJalanRusak.Web.Services.Toastr;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DeteksiJalanRusak.Web.Controllers;

public class AnalisisController : Controller
{
    private readonly AppDbContext _context;
    private readonly IToastrNotificationService _notificationService;
    private readonly ILogger<AnalisisController> _logger;

    public AnalisisController(
        AppDbContext context,
        IToastrNotificationService notificationService,
        ILogger<AnalisisController> logger)
    {
        _context = context;
        _notificationService = notificationService;
        _logger = logger;
    }

    public async Task<IActionResult> Detail(int id)
    {
        var analisis = await _context
            .TblAnalisis
            .Include(x => x.DaftarSegmen).ThenInclude(x => x.DaftarFoto).ThenInclude(x => x.DaftarKerusakan)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (analisis is null) return NotFound();

        return View(analisis);
    }

    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if (await _context.TblAnalisis.AnyAsync(x => x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        var analisis = new Analisis
        {
            Lokasi = vm.Lokasi,
            Nama = vm.Nama,
            Pembuat = vm.Pembuat
        };

        _context.TblAnalisis.Add(analisis);
        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Edit(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        return View(new EditVM
        {
            Id = id,
            Nama = analisis.Nama,
            Lokasi = analisis.Lokasi,
            Pembuat = analisis.Pembuat
        });
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == vm.Id);
        if (analisis is null) return NotFound();

        if (await _context.TblAnalisis.AnyAsync(x => x.Id != analisis.Id && x.Nama.ToLower() == vm.Nama.ToLower()))
        {
            ModelState.AddModelError(nameof(vm.Nama), "Sudah digunakan");
            return View(vm);
        }

        analisis.Nama = vm.Nama;
        analisis.Lokasi = vm.Lokasi;
        analisis.Pembuat = vm.Pembuat;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public async Task<IActionResult> Hapus(int id)
    {
        var analisis = await _context.TblAnalisis.FirstOrDefaultAsync(x => x.Id == id);
        if (analisis is null) return NotFound();

        _context.TblAnalisis.Remove(analisis);

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());

            return RedirectToAction(nameof(Index));
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectToAction("Index", "Home");
    }
}

DeteksiJalanRusak.Web/Controllers/SegmenController.cs
using DeteksiJalanRusak.Web.Configurations;
using DeteksiJalanRusak.Web.Database;
using DeteksiJalanRusak.Web.Entities;
using DeteksiJalanRusak.Web.Extensions;
using DeteksiJalanRusak.Web.Models;
using DeteksiJalanRusak.Web.Models.SegmenModels;
using DeteksiJalanRusak.Web.Services.FileServices;
using DeteksiJalanRusak.Web.Services.Toastr;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkiaSharp;
using YoloDotNet;
using YoloDotNet.Core;
using YoloDotNet.Enums;
using YoloDotNet.Extensions;
using YoloDotNet.Models;

namespace DeteksiJalanRusak.Web.Controllers;

public class SegmenController : Controller
{
    public const double LEBAR_KERTASA4_CM = 21;
    public const double PANJANG_KERTASA4_CM = 29.7;
    public const double LEBAR_KERTASA4_M = LEBAR_KERTASA4_CM / 100;
    public const double PANJANG_KERTASA4_M = PANJANG_KERTASA4_CM / 100;
    public const double LUAS_KERTASA4_CM2 = LEBAR_KERTASA4_CM * PANJANG_KERTASA4_CM;
    public const double LUAS_KERTASA4_M2 = LUAS_KERTASA4_CM2 / 10000;

    private readonly SegmentationDrawingOptions _drawingOptions;
    private readonly ModelConfigurationOptions _modelConfigurationOptions;
    private readonly AppDbContext _appDbContext;
    private readonly IWebHostEnvironment _webHostEnvironment;
    private readonly IFileService _fileService;
    private readonly IToastrNotificationService _notificationService;
    private readonly ILogger<SegmenController> _logger;

    public SegmenController(
        ModelConfigurationOptions modelConfigurationOptions,
        AppDbContext appDbContext,
        IWebHostEnvironment webHostEnvironment,
        IFileService fileService,
        IToastrNotificationService notificationService,
        ILogger<SegmenController> logger)
    {
        _drawingOptions = new SegmentationDrawingOptions
        {
            DrawBoundingBoxes = true,
            DrawConfidenceScore = true,
            DrawLabels = true,
            EnableFontShadow = true,
            Font = SKTypeface.Default,
            FontSize = 18,
            FontColor = SKColors.White,
            DrawLabelBackground = true,
            EnableDynamicScaling = true,
            BorderThickness = 2,
            BoundingBoxOpacity = 128,
            DrawSegmentationPixelMask = true
        };
        _modelConfigurationOptions = modelConfigurationOptions;
        _appDbContext = appDbContext;
        _webHostEnvironment = webHostEnvironment;
        _fileService = fileService;
        _notificationService = notificationService;
        _logger = logger;
    }

    public IActionResult Tambah(int idAnalisis) => View(new TambahVM { IdAnalisis = idAnalisis });

    [HttpPost]
    [RequestSizeLimit(100_000_000)]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var analisis = await _appDbContext.TblAnalisis.FirstOrDefaultAsync(x => x.Id == vm.IdAnalisis);
        if (analisis is null)
        {
            _notificationService.AddError("Analisis tidak ditemukan");
            return RedirectToActionPermanent("Index", "Analisis");
        }

        var tasks = vm.FormFiles.Select(x => _fileService.ProcessFormFile<TambahVM>(x, [".jpg", ".jpeg", ".png"], 0, long.MaxValue)).ToList();
        var daftarFoto = await Task.WhenAll(tasks);

        var failures = daftarFoto.Where(x => x.IsFailure);
        if (failures.Any())
        {
            ModelState.AddModelError(nameof(vm.FormFiles), string.Join("\n", failures.Select(x => x.Error.Message)));
            return View(vm);
        }

        var segmen = new Segmen
        {
            LuasSampel = vm.LuasSampel,
            Analisis = analisis,
            DaftarFoto = []
        };

        using var yolo = new Yolo(new YoloOptions
        {
            OnnxModel = _modelConfigurationOptions.FilePath,
            ExecutionProvider = new CpuExecutionProvider(),
            ImageResize = ImageResize.Stretched,
            SamplingOptions = new(SKFilterMode.Nearest, SKMipmapMode.None)
        });

        foreach (var foto in daftarFoto)
        {
            using var image = SKBitmap.Decode(foto.Value);
            var results = yolo.RunSegmentation(image, confidence: 0.5, pixelConfedence: 0.5, iou: 0.7);
            image.Draw(results, _drawingOptions);

            var fotoKerusakan = new FotoKerusakan
            {
                AdaKertas = false,
                FileName = vm.FormFiles[Array.IndexOf(daftarFoto, foto)].FileName,
                Image = image.Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                Lebar = image.Width,
                Tinggi = image.Height,
                DaftarKerusakan = [.. results.Where(x => x.Label.Name != LabelEnum.Kertas.ToString()).Select(x => new Kerusakan
                {
                    Label = x.Label.Name.DehumanizeTo<LabelEnum>(),
                    Mask = x.BitPackedPixelMask.UnpackToBitmap(x.BoundingBox.Width, x.BoundingBox.Height).Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                    Luas = 0,
                    Panjang = 0,
                    Lebar = 0,
                    LebarPiksel = 0,
                    TinggiPiksel = 0,
                })]
            };

            var kertas = results.FirstOrDefault(s => s.Label.Name == LabelEnum.Kertas.ToString());

            if (kertas is not null)
            {
                var totalPixel = kertas.BitPackedPixelMask.Count(x => x != 0);
                var m2PerPixel = LUAS_KERTASA4_M2 / totalPixel;

                var mPerPixel = PANJANG_KERTASA4_M /
                    (kertas.BoundingBox.Width > kertas.BoundingBox.Height ? kertas.BoundingBox.Width : kertas.BoundingBox.Height);

                fotoKerusakan.AdaKertas = true;

                fotoKerusakan.MaskKertas = kertas.BitPackedPixelMask.UnpackToBitmap(kertas.BoundingBox.Width, kertas.BoundingBox.Height).Encode(SKEncodedImageFormat.Jpeg, 70).ToArray();

                fotoKerusakan.M2PerPiksel = m2PerPixel;
                fotoKerusakan.MPerPiksel = mPerPixel;
                fotoKerusakan.LuasKertas = kertas.BitPackedPixelMask.Count(x => x != 0) * m2PerPixel;
                fotoKerusakan.PanjangKertas = kertas.BoundingBox.Height * mPerPixel;
                fotoKerusakan.LebarKertas = kertas.BoundingBox.Width * mPerPixel;
                fotoKerusakan.TinggiPikselKertas = kertas.BoundingBox.Height;
                fotoKerusakan.LebarPikselKertas = kertas.BoundingBox.Width;

                fotoKerusakan.DaftarKerusakan = [];

                foreach (var segmentation in results.Where(x => x.Label.Name != LabelEnum.Kertas.ToString()))
                {
                    fotoKerusakan.DaftarKerusakan.Add(new Kerusakan
                    {
                        Label = segmentation.Label.Name.DehumanizeTo<LabelEnum>(),
                        Mask = segmentation
                            .BitPackedPixelMask
                            .UnpackToBitmap(segmentation.BoundingBox.Width, segmentation.BoundingBox.Height)
                            .Encode(SKEncodedImageFormat.Jpeg, 70).ToArray(),
                        Luas = segmentation.BitPackedPixelMask.Count(x => x != 0) * m2PerPixel,
                        Panjang = segmentation.BoundingBox.Height * mPerPixel,
                        Lebar = segmentation.BoundingBox.Width * mPerPixel,
                        TinggiPiksel = segmentation.BoundingBox.Height,
                        LebarPiksel = segmentation.BoundingBox.Width,
                    });
                }
            }

            segmen.DaftarFoto.Add(fotoKerusakan);
        }

        _appDbContext.TblSegmen.Add(segmen);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());
            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");

        return RedirectToActionPermanent("Detail", new { id = segmen.Id });
    }

    public async Task<IActionResult> Edit(int id, string? returnUrl = null)
    {
        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == id);
        if (segmen is null) return NotFound();

        return View(new EditVM
        {
            Id = id,
            LuasSampel = segmen.LuasSampel,
            ReturnUrl = returnUrl ?? Url.ActionLink("Detail", "Analisis", new { id = segmen.Analisis.Id })!
        });
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == vm.Id);
        if (segmen is null) return NotFound();

        segmen.LuasSampel = vm.LuasSampel;

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            _notificationService.AddError("Simpan Gagal");
            _logger.LogError(ex.ToString());
            return View(vm);
        }

        _notificationService.AddSuccess("Simpan Berhasil");
        return RedirectPermanent(vm.ReturnUrl);
    }

    public async Task<IActionResult> Detail(int id)
    {
        var segmen = await _appDbContext
            .TblSegmen
            .Include(x => x.Analisis)
            .Include(x => x.DaftarFoto).ThenInclude(x => x.DaftarKerusakan)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (segmen is null) return NotFound();

        return View(segmen);
    }

    [HttpPost]
    public async Task<IActionResult> Hapus(int id)
    {
        var segmen = await _appDbContext.TblSegmen.Include(x => x.Analisis).FirstOrDefaultAsync(x => x.Id == id);
        if (segmen is null) return NotFound();

        var idAnalisis = segmen.Analisis.Id;

        _appDbContext.TblSegmen.Remove(segmen);

DeteksiJalanRusak.Web/Views/Analisis/Detail.cshtml
@model Analisis

@{
    ViewData["Title"] = "Detail Analisis";
}

<div class="card card-secondary mb-2">
    <div class="card-header">
        <h4>Detail Analisis</h4>
    </div>

    <div class="card-body pt-0">
        <p>Nama : @Model.Nama</p>
        <p>Lokasi : @Model.Lokasi</p>
        <p>Pembuat : @Model.Pembuat</p>
    </div>
</div>

<div class="card mb-2">
    <div class="card-header">
        <h4>Hasil Metode PCI</h4>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class ="table table-striped table-hover" id="table-akun1">
                <thead>
                    <tr>
                        <th>PCI<sub>Avg</sub></th>
                        <th>Kondisi</th>
                        <th>Jenis Penanganan</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.RataRataPCI</td>
                        <td>@Model.Kondisi</td>
                        <td>@Model.JenisPenanganan</td>
                    </tr>
                </tbody>
            </table>
        </div>        
    </div>
</div>

<div class="card">
    <div class="card-header">
        <h4>Daftar Segmen</h4>
    </div>

    <div class="card-body">

        <a class="btn btn-icon icon-left btn-primary mb-3" asp-action="Tambah" asp-controller="Segmen" asp-route-idAnalisis="@Model.Id"><i class="fas fa-plus"></i> Tambah</a>

        <div class="table-responsive">
            <table class="table table-striped table-hover" id="table-akun2">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Luas Sampel (m<sup>2</sup>)</th>
                        <th>PCI</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.DaftarSegmen.Count; i++)
                    {
                        var segmen = Model.DaftarSegmen[i];
                        var pciResult = segmen.MetodePCI();
                        <tr>
                            <td>@(i + 1)</td>
                            <td>@segmen.LuasSampel</td>
                            @if (pciResult is not null)
                            {
                                <td>
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Mi</th>
                                                <th>q<sub>Max</sub></th>
                                                <th>TDV<sub>Max</sub></th>
                                                <th>CDV<sub>Max</sub></th>
                                                <th>PCI</th>
                                                <th>Kondisi</th>
                                                <th>Jenis Penanganan</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@pciResult.MI</td>
                                                <td>@pciResult.QMax</td>
                                                <td>@pciResult.TDVMax</td>
                                                <td>@pciResult.CDVMax</td>
                                                <td>@pciResult.PCI</td>
                                                <td>@pciResult.Kondisi</td>
                                                <td>@pciResult.JenisPenanganan</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                            }
                            else
                            {
                                <td>Tidak Ada Hasil</td>
                            }
                            <td>
                                <div class="d-flex">
                                    <a asp-controller="Segmen" asp-action="Detail" asp-route-id="@segmen.Id" class="btn btn-icon icon-left btn-warning mr-1"><i class="fas fa-eye"></i></a>
                                    <a asp-controller="Segmen" asp-action="Edit" asp-route-id="@segmen.Id" asp-route-returnUrl="@Context.Request.AbsoluteUri()" class="btn btn-icon icon-left btn-secondary mr-1"><i class="fas fa-pen"></i></a>
                                    <form asp-controller="Segmen" asp-action="Hapus" asp-route-id="@segmen.Id" style="display:inherit">
                                        <button type="submit" class="btn btn-icon icon-left btn-danger"><i class="fas fa-trash"></i></button>
                                    </form>
                                </div>
 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

DeteksiJalanRusak.Web/Views/Analisis/Edit.cshtml
@using DeteksiJalanRusak.Web.Models.AnalisisModels
@model EditVM

@{
    ViewData["Title"] = "Edit Analisis";
}

<div class="card card-primary">
    <div class="card-header">
        <h4>Edit Analisis</h4>
    </div>

    <div class="card-body">
        <form asp-action="Edit" asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Nama"></label>
                <input asp-for="@Model.Nama" class="form-control" />
                <span asp-validation-for="@Model.Nama" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Lokasi"></label>
                <input asp-for="@Model.Lokasi" class="form-control" />
                <span asp-validation-for="@Model.Lokasi" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Pembuat"></label>
                <input asp-for="@Model.Pembuat" class="form-control" />
                <span asp-validation-for="@Model.Pembuat" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a asp-action="Index" asp-controller="Home" class="btn btn-danger">Batal</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DeteksiJalanRusak.Web/Views/Analisis/Tambah.cshtml
@using DeteksiJalanRusak.Web.Models.AnalisisModels
@model TambahVM

@{
    ViewData["Title"] = "Tambah Analisis";
}

<div class="card card-primary">
    <div class="card-header">
        <h4>Buat Analisis Baru</h4>
    </div>

    <div class="card-body">
        <form asp-action="Tambah">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="@Model.Nama"></label>
                <input asp-for="@Model.Nama" class="form-control" />
                <span asp-validation-for="@Model.Nama" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Lokasi"></label>
                <input asp-for="@Model.Lokasi" class="form-control" />
                <span asp-validation-for="@Model.Lokasi" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.Pembuat"></label>
                <input asp-for="@Model.Pembuat" class="form-control" />
                <span asp-validation-for="@Model.Pembuat" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a asp-action="Index" asp-controller="Home" class="btn btn-danger">Batal</a>
            </div>
        </form>

    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}